### PR TITLE
fix: [nestjs integration] fastify HTTP adapter detection now works correctly for response headers

### PR DESCRIPTION
**Pull request by eugene-yaroslavtsev**
~~Closes #<issue>~~ (didn't make issue for this bug, just made PR right away)

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/triggerdotdev/trigger.dev/blob/main/CONTRIBUTING.md)
- [x] The PR title follows the convention.
- [x] I ran and tested the code works

---

## Testing

Pointed my local application where I first encountered this bug at my new version and verified:

- ✅ broken fastify response behavior now fixed
- ✅ express.js response behavior didn't break due to this fix

---

## Changelog

- fixed a bug where Fastify responses were incorrectly processed as Express due to overlapping method names.
- introduced type guards to differentiate between Express and Fastify response objects.
- bumping @trigger.dev/nestjs patch version to 2.3.19

### CODE REVIEW

**Review by matt-aitken — APPROVED** [review]
Thanks this is great.

**Comment by eugene-yaroslavtsev** [comment]
> @matt-aitken E2E tests seem to fail due to auth issue, perhaps because this is coming from my own fork? Any idea what I should do here? 🤔
> 
> ```
> Run docker/login-action@v2
>   with:
>     ecr: auto
>     logout: true
> Error: Username and password required
> ```

@matt-aitken know you're busy man, just a friendly ping 😃

**Comment by eugene-yaroslavtsev** [comment]
@matt-aitken - I checked the merge from master:

Screenshot 2024-03-17 at 10 37 40 PM

Didn't seem to overlap at all with my code. Let's get this thing merged!

**Comment by eugene-yaroslavtsev** [comment]
@ericallam - I think Matt's a busy - would you mind merging this in? 🙇 It'll def help any folks who are using NestJS with Fastify (which is btw the superior choice in terms of perf compared to express)

**Review by matt-aitken — APPROVED** [review]

**Comment by matt-aitken** [comment]
@eugene-yaroslavtsev sorry it's taken a while to merge this. 

We have a lot of unpublished package changes that need proper testing before release. To check that the v3 changes don't break anything in v2.

This is merged and I've published a special release of the packages for you: 

You can use this to switch to them:
```
npx @trigger.dev/cli@latest update -t 0.0.0-nestfix-20240322145612
```

**Pull request merged**
