### PR TITLE
chore: updated prisma from version 4.16.0 to 5.1.0

### PR DESCRIPTION
**Pull request by Chigala**
updated prisma to version 5.1.0

ref: #243

### CODE REVIEW

**Review by matt-aitken — CHANGES_REQUESTED** [review]
In v5 Prisma have made it so you can't pass a single value to a field that accepts an array.

This impacts out EventDispatcher event column.

If you run:
```pnpm run typecheck```

You'll see there are some errors:
```sh
webapp:typecheck: app/services/jobs/registerJob.server.ts(439,13): error TS2322: Type 'string' is not assignable to type 'string[] | EventDispatcherCreateeventInput | undefined'.
webapp:typecheck: app/services/triggers/registerDynamicSchedule.server.ts(82,9): error TS2322: Type 'string' is not assignable to type 'string[] | EventDispatcherCreateeventInput | undefined'.
webapp:typecheck: app/services/triggers/registerTriggerSource.server.ts(79,13): error TS2322: Type '(string | string[]) & (string | string[] | undefined)' is not assignable to type 'string[] | EventDispatcherCreateeventInput | undefined'.
webapp:typecheck:   Type 'string' is not assignable to type 'string[] | EventDispatcherCreateeventInput | undefined'.
webapp:typecheck: app/services/triggers/registerTriggerSource.server.ts(89,13): error TS2322: Type '(string | string[]) & (string | string[] | undefined)' is not assignable to type 'string[] | EventDispatcherUpdateeventInput | undefined'.
webapp:typecheck:   Type 'string' is not assignable to type 'string[] | EventDispatcherUpdateeventInput | undefined'.
```

If you're not getting type errors in VSCode in those files, run the "TypeScript: Restart TS Server" command from the VSCode Command Palette. Sometimes when running Prisma updates it doesn't update the TS hints.

**Comment by ericallam** [comment]
@Chigala if you have time could you take a look at those TS errors and get those fixed in this PR? Would love to merge this in ASAP 👍

**Comment by Chigala** [comment]
I totally forgot about this, I'll have it fixed.

**Review by matt-aitken — APPROVED** [review]

**Comment by matt-aitken** [comment]
@Chigala great work!

**Pull request merged**
