### PR TITLE
feat: [TRI-1251] Framework: support for Redwood.js

### LINKED ISSUE #448: [TRI-1251] Framework: support for Redwood.js
# Build support for Redwood into Trigger.dev

**_Please make sure to use Typescript for all code_**

### Task 1 - Redwood Adaptor
- [ ] Create a new folder in `packages` called `redwood`
- [ ] Create the adaptor for Redwood. Use [this Next.js adaptor](https://github.com/triggerdotdev/trigger.dev/blob/main/packages/nextjs/src/index.ts) code as reference when creating yours. Include all setup configurations to fully support the framework, e.g. Next.js requires adaptor support for both App and Pages routers.
- [ ] Create a basic Redwood project that uses the adaptor in `examples/redwood` folder. Include a basic Job in Trigger.dev, e.g. a simple Job that just does a delay inside it. Screen grab the full Run dashboard page showing it successfully worked. Here are examples of how to do cross-project references in [package.json](https://github.com/triggerdotdev/trigger.dev/blob/aae143d96e1cd3c2b2b2ccb5120f75651a4261d0/examples/nextjs-example/package.json#L14) and [tsconfig.json](https://github.com/triggerdotdev/trigger.dev/blob/aae143d96e1cd3c2b2b2ccb5120f75651a4261d0/examples/nextjs-example/tsconfig.json#L31).
- [ ] Provide a screen grab of your terminal showing the Adaptor is working

### Task 2 – Add a README.md file
- [ ] Create a new README.md file inside the `packages/redwood` folder and copy in the contents from `packages/nextjs/README.md`. Adjust the wording to reference Redwood where needed, including updating the the URLs.

### Task 3 – Write the documentation
- [ ] Locate the `manual-setup-redwood.mdx` folder in `/docs/_snippets/`. Use this file to write your documentation, overwriting any contents of that file. Follow the structure of [this Next.js example](https://trigger.dev/docs/documentation/guides/manual/nextjs) for reference when writing yours.
- [ ] Update the table at the bottom of the `client-adaptors.mdx` page with the framework you’ve worked on.

### Task 4 – Update the webapp onboarding
- [ ] In the `route.tsx` page located in `_app.orgs.$organizationSlug.projects.$projectParam.setup.redwood` replace the `<FrameworkComingSoon/>` component with your new onboarding steps. Follow the same structure as the Next.js example when creating your own. Ignore the very top step for adding this framework to a new project, just focus on the steps to add it to an existing project (so don’t include the `<RadioGroup/>` toggle selector at the top). Make sure you also include the `useProjectSetupComplete();` hook at the top of the page – this triggers a particle effect when the new job is successfully created and redirects to the Jobs list 🥳 .
- [ ] In the `FrameworkSelector.tsx` file, add “supported” to the framework you’ve worked on.
CleanShot 2023-09-07 at 16 42 14

<sub>[TRI-1251](https://linear.app/triggerdotdev/issue/TRI-1251/framework-support-for-redwoodjs)</sub>

### PR DESCRIPTION
**Pull request by rishi-raj-jain**
fix #448
/claim #448

### CODE REVIEW

**Comment by rishi-raj-jain** [comment]
Update: I'm still working on it.

**Comment by matt-aitken** [comment]
@rishi-raj-jain is it ready to review now?

**Comment by rishi-raj-jain** [comment]
@matt-aitken I'm undergoing a cornea procedure, would it be okay if this is delayed by a day more on my end?

**Comment by matt-aitken** [comment]
@rishi-raj-jain yep no problem, just let me know when this is ready for review. I hope it all goes well 🙏

**Comment by rishi-raj-jain** [comment]
Continuing https://github.com/triggerdotdev/trigger.dev/pull/598

**Pull request closed without merging**
