### PR TITLE
created the manual setup guide doc

### LINKED ISSUE #277: [TRI-945] Add a manual project setup guide to the docs
We have a quickstart which uses the CLI init command. But we don't have a manual installation guide anywhere.

* The manual installation guide should live in the guides sidebar.
* It would have steps to install packages
* It would have steps to add/modify the correct files and folders (everything the init command does).

For inspiration, create-next-app have good manual installation steps here: [https://nextjs.org/docs/getting-started/installation#manual-installation](https://nextjs.org/docs/getting-started/installation#manual-installation)

<sub>From [SyncLinear.com](https://synclinear.com) | [TRI-945](https://linear.app/triggerdotdev/issue/TRI-945/add-a-manual-project-setup-guide-to-the-docs)</sub>

### PR DESCRIPTION
**Pull request by Chigala**
### Description
This pull request adds comprehensive documentation for setting up a Next.js project with Trigger.dev. The guide provides step-by-step instructions, code snippets, and explanations for each stage of the setup process. It covers configuring the Trigger Client, defining jobs, creating API routes, setting environment variables, running the Next.js site, and using the CLI dev command. The documentation is provided in a clear and organized manner to assist developers in seamlessly integrating Trigger.dev into their projects.

### Changes
- Created a new markdown file `manual-setup-guide.md` in the `docs` directory.
- Added detailed instructions for each step of the setup process, along with relevant code snippets.
- Included explanations and optional advanced setup steps for running Next.js server with CLI.
- Added title and description metadata to the document for clarity and organization.

Closes #277

### CODE REVIEW

**Comment by yashug** [comment]
@Chigala i can see two missing pieces

1. mint.json file update with the new added mdx file
2. adding configuration to package.json file

**Comment by matt-aitken** [comment]
@Chigala went with @yashug with this one but gave you a tip for this PR. Thanks!

**Comment by Chigala** [comment]
Thanks a lot

**Pull request closed without merging**
