### PR TITLE
Get help icon and twitter text modifications 

### LINKED ISSUE #632: feat: changing getting help icons
### Is your feature request related to a problem? Please describe.

As twitter is now X ,the icon should be fixed and also other cards can aslo have a better icon
image

### Describe the solution you'd like to see

changing icons for these cards and enhancing them with better icons for a more better look

### Describe alternate solutions

if not all twitter should be changed to X

## I WOULD LIKE TO WORK ON THIS ISSUE

### PR DESCRIPTION
**Pull request by shelar1423**
Closes #632 

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/triggerdotdev/trigger.dev/blob/main/CONTRIBUTING.md)
- [x] The PR title follows the convention.
- [x] I ran and tested the code works

---

## Testing

Changed icons and ran it on local host and enusred it works the way it should.

---

## Changelog

icons on Getting help changed to new ones for better look and changed"twitter" ->"X(Twitter)"
---

## Screenshots

before :
image

After:
image

💯

### CODE REVIEW

**Comment by matt-aitken** [comment]
@samejr @D-K-P this is one for you

**Comment by shelar1423** [comment]
> @samejr @D-K-P this is one for you

Hey@matt-aitken didn't understand what you meant here?

**Comment by D-K-P** [comment]
@shelar1423 the X icon and star are great but the call icon isn’t good, should just be a solid phone if there is one, and the right size. Also the name should be ‘X (Twitter)’ with a space

**Comment by shelar1423** [comment]
image
@D-K-P  have a review

**Pull request merged**
