### PR TITLE
[TRI-1333] : Upgrade all packages to use Node18 and use fetch instead node-fetch

### LINKED ISSUE #525: [TRI-1333] [TRI-1332] Upgrade all packages/* and use fetch instead of node-fetch
## Problem

Our packages currently support Node 16–17. This means we can't use `fetch` and we can't support some modern deployment platforms like Cloudflare/Vercel edge functions.

Node v18 is now LTS and v16 has entered "end-of-life" with no official support.

## Solution

* Set the engines.node property in all of the packages/\*/package.json files.
* Upgrade all packages/\* to support Node v18. 
* Change fetch to node-fetch
* Fix any other issues
* Ensure that typechecking has no errors: `pnpm run --filter "./packages/**" typecheck`

<sub>From [SyncLinear.com](https://synclinear.com) | [TRI-1332](https://linear.app/triggerdotdev/issue/TRI-1332/upgrade-all-packages-and-use-fetch-instead-of-node-fetch)</sub>

<sub>[TRI-1333](https://linear.app/triggerdotdev/issue/TRI-1333/[tri-1332]-upgrade-all-packages-and-use-fetch-instead-of-node-fetch)</sub>

### PR DESCRIPTION
**Pull request by Rutam21**
Closes #525 

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/triggerdotdev/trigger.dev/blob/main/CONTRIBUTING.md)
- [x] The PR title follows the convention.
- [x] I ran and tested the code works

---

## Testing

**Typechecking for the Packages folder has been done as mentioned in the ticket.**

```bash
pnpm run --filter "./packages/**" typecheck
```

typecheck

```
Smoke Testing has been done as suggested by @ericallam .
```

- **`Events` and `Delays` jobs were run using `pnpm run events/delay`. The commands executed succesfully and the jobs started listening on Port 8080.**

delay

- **Then the triggers were run using `pnpm run dev trigger` that refreshed the job catalog on the Trigger Cloud dashboard.**

trigger

- **If any changes were made in the code to either enable or disable a particular job, the trigger kept refreshing the job catalog.**

JobRefresh

- **Job were properly listed on the Jon dashboard on Trigger Cloud.**

CurrentJobs

- **Jobs were tested on the Cloud Dashboard and were running successfully.**

DelayRun

Delay Runs List

- **`pnpm run --filter "!./apps/**" typecheck` was also run in the root to make sure the types are in-tact.** 

Root TypeCheck

---

## Changelog

- All the Packages are updated to use the Node v18.0.0 LTS from now on.
- Minor fixes are done to support fetch and its available functions.
- `Node-Fetch` imports and dependency are removed in all packages and `fetch` is getting used as the native function as supported by Node 18 now.

---

> Note: Changeset has been added as a Patch release only.

### CODE REVIEW

**Comment by Rutam21** [comment]
@ericallam Please review and suggest changes, if any. Thanks.

**Comment by ericallam** [comment]
At first glance this is looking good. Will try and find time over the weekend to review but will get to it by Monday latest 👍

**Comment by ericallam** [comment]
Pulled this down and looks like there is an issue with the pnpm-lock.yaml file as I'm getting this error when running `pnpm install`:

```sh
Ignoring broken lockfile at /Users/eric/code/triggerdotdev/trigger.dev: Lockfile /Users/eric/code/triggerdotdev/trigger.dev/pnpm-lock.yaml not compatible with current pnpm
```

Can you make sure you are using `pnpm@7.18.1`

**Comment by Rutam21** [comment]
@ericallam I have updated the `pnpm.lock` file as per pnpm v7.18.1. My curent system pnpm is also set to 7.18.1.

pnpm version

Please review and suggest changes, if any. Thank you.

**Comment by ericallam** [comment]
Unfortunately because of the original usage of pnpm v8, when you ran `pnpm install` with pnpm v7 in this branch it caused a complete re-creation of the pnpm-lock.yaml file, resulting in massive changes to the dependencies that are installed (basically as if there was no pnpm-lock.yaml file to begin with). To be able to merge this PR more quickly I would suggest reverting all changes made to the pnpm-lock.yaml file from the beginning of these PR and re-run `pnpm install`, starting from the last known good point. One way you could do that is grabbing the contents of pnpm-lock.yaml from the commit just before your commits and copy/pasting into your local pnpm-lock.yaml file and then running `pnpm install` and then committing/pushing.

**Comment by Rutam21** [comment]
@ericallam Thanks for the suggestion. I grabbed the lock file from the main branch of my fork from which this PR branch was created and then did a `pnpm i` and pushed the updated the lock file back. Hope this resolves all the previous version conflicts.

**Pull request merged**
