### PR TITLE
chore: upgrade zod to 3.22.3

### LINKED ISSUE #548: Upgrade Zod across all packages and webapp to 3.22.3
Zod recently released a patch to fix a ReDoS vulnerability in email regex, and we should update all our packages that use zod to use the new version, as well as the webapp. This should be a `patch` update.

https://github.com/colinhacks/zod/pull/2824

### PR DESCRIPTION
**Pull request by hmacr**
Closes #548 

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/triggerdotdev/trigger.dev/blob/main/CONTRIBUTING.md)
- [x] The PR title follows the convention.
- [x] I ran and tested the code works

---

## Testing

Ran E2E tests to verify they succeeded.

---

## Changelog

Upgrade zod library to 3.22.3 across all packages.

---

## Screenshots

Screenshot 2023-10-04 at 7 02 21 PM

💯

### CODE REVIEW

**Comment by ericallam** [comment]
This looks great! Could you resolve the conflicts and then this PR can be merged 👍

**Comment by hmacr** [comment]
Thanks! I've rebased the PR.

**Comment by ericallam** [comment]
@hmacr unfortunately the pnpm-lock.yaml file in this PR is broken, probably because of a bad merge or conflict resolution. Might be easiest to close this PR and redo the changes on top of the newest main broken lockfile. Doing a `pnpm install` with a broken lockfile completely recreates the lockfile which is definitely not what we want.

**Comment by hmacr** [comment]
@ericallam ah ok. Let me close this and create a new PR.

**Comment by hmacr** [comment]
@ericallam Raised a new PR - #570. Please check.

Unfortunately, I was using pnpm v8 (instead of the recommended v7). v8 introduced a change in the lockfile format, hence it resulted in too many changes.

**Pull request closed without merging**
