### PR TITLE
[TRI-1364] feat: Switch to Sonner toasts #555

### LINKED ISSUE #555: [TRI-1364] feat: Switch to Sonner toasts
We currently use toasts in our dashboard in a few places which are powered by "react-hot-toast". We should upgrade to Sonner toasts as they have some pretty cool features and look great:

https://github.com/emilkowalski/sonner

<sub>[TRI-1364](https://linear.app/triggerdotdev/issue/TRI-1364/feat-switch-to-sonner-toasts)</sub>

### PR DESCRIPTION
**Pull request by arjunindia**
Closes #555

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/triggerdotdev/trigger.dev/blob/main/CONTRIBUTING.md)
- [x] The PR title follows the convention.
- [x] I ran and tested the code works

---

## Testing

- Created new stories for UIs and toasts
---

## Changelog

- Removes react-hot-toast based Toast
- Adds Sonner based toast

---

## Screenshots

image

💯

### CODE REVIEW

**Comment by ericallam** [comment]
I've recorded a video of some issues with this PR. As you can see in the video the toasts aren't right-aligned against the bottom of the window. They are also transparent and don't work very well when there are multiple toasts:


https://github.com/triggerdotdev/trigger.dev/assets/534/b8494410-708b-41a7-8dda-b7918b9736be

**Comment by arjunindia** [comment]
@ericallam  can you check the latest revision?

**Comment by ericallam** [comment]
Will do! In the meantime can you make a similar screencast as mine so I can visually inspect the changes?

**Comment by arjunindia** [comment]
https://github.com/triggerdotdev/trigger.dev/assets/37960163/aacae2e4-915b-4c8c-93af-1378eb87c9d8

Here you go

**Comment by ericallam** [comment]
Pulled this down and looks like there is an issue with the pnpm-lock.yaml file as I'm getting this error when running `pnpm install`:

```sh
Ignoring broken lockfile at /Users/eric/code/triggerdotdev/trigger.dev: Lockfile /Users/eric/code/triggerdotdev/trigger.dev/pnpm-lock.yaml not compatible with current pnpm
```

Can you make sure you are using `pnpm@7.18.1`

**Comment by ericallam** [comment]
Also ran into this same issue in another PR and left a comment just now about how to recover from this: 

https://github.com/triggerdotdev/trigger.dev/pull/581#issuecomment-1753869773

**Comment by arjunindia** [comment]
I seem to have messed up :(

**Pull request closed without merging**
