### PR TITLE
feat: allow sendEvent to update an existing event

### LINKED ISSUE #604: [TRI-1395] Calling `sendEvent` with a duplicate ID and a `deliverAt` or `deliverAfter` option should update the existing event
Currently calling `sendEvent` with a duplicate event ID doesn't update the event at all, but if the event hasn't been delivered yet (it has a delivery date in the future) we should update the events:

- payload
- context
- deliverAt

<sub>[TRI-1395](https://linear.app/triggerdotdev/issue/TRI-1395/calling-sendevent-with-a-duplicate-id-and-a-deliverat-or-deliverafter)</sub>

### PR DESCRIPTION
**Pull request by hmacr**
Closes #604 

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/triggerdotdev/trigger.dev/blob/main/CONTRIBUTING.md)
- [x] The PR title follows the convention.
- [x] I ran and tested the code works

---

## Testing

- Verified event creation and subsequent run.
  - without deliverAt / deliverAfter.
  - with deliverAt / deliverAfter.
- Verified event updation and subsequent run.
  - without deliverAt / deliverAfter.
  - with deliverAt / deliverAfter.
- Verified event doesn't get updated when it is within the threshold window.

---

## Changelog

- Implement event update for duplicate requests.
- Use a threshold window to determine if the update should proceed.

💯

### CODE REVIEW

**Comment by ericallam** [comment]
@hmacr great work on this 👏. If you are interested could you take a look at this issue: https://github.com/triggerdotdev/trigger.dev/issues/604

**Comment by hmacr** [comment]
> @hmacr great work on this 👏. If you are interested could you take a look at this issue: #604

@ericallam The issue referenced, points to the one that's resolved by this PR. Did you mean to link a different issue?

**Comment by ericallam** [comment]
@hmacr oops, I meant to link to this one: https://github.com/triggerdotdev/trigger.dev/issues/565

**Comment by hmacr** [comment]
> @hmacr oops, I meant to link to this one: #565

@ericallam Sure! I'll have a look 👍

**Pull request merged**
