### PR TITLE
feat: Add job management API endpoints

### PR DESCRIPTION
**Pull request by neo773**
This PR adds job management API endpoints exposed via a new class named `TriggerManagementAPI`

image

/claim #388

### CODE REVIEW

**Comment by ericallam** [comment]
Thanks for this @neo773! Our front-end guru who will be picking this front-end design up is away for the week on holiday so it might be awhile before we can get this one in to production.

**Comment by neo773** [comment]
@ericallam Any updates?

**Comment by ericallam** [comment]
Sorry this has been in a holding pattern, our designer @samejr is hopefully going to get to this next week 👍

**Review by matt-aitken — CHANGES_REQUESTED** [review]
I think all of the API endpoints should be at this path: `/manage/api/v1/`.

It's a separate API from the main one.

**Comment by samejr** [comment]
@neo773 working on the UI now...

**Comment by samejr** [comment]
Hey @neo773 thanks for working on this issue. I'm going to close this PR now as we need to rework some more things before we can implement it, but i've paid the bounty in the meantime.

**Pull request closed without merging**
