### PR TITLE
Improved the Airtable integration documentation

### LINKED ISSUE #665: [TRI-1431] Improve the Airtable integration documentation
## Overview:

Update the [Airtable integration documentation](https://trigger.dev/docs/integrations/apis/airtable) so it is much easier to use as a reference.

We have just overhauled our [GitHub documentation](https://trigger.dev/docs/integrations/apis/github) and would like all of the rest of our integrations to follow the same structure.

*Please use the references and resources at the bottom of this post to complete this issue.*

### Airtable overview & authentication:

This page is currently [this](https://trigger.dev/docs/integrations/apis/airtable).

* **Page Title:** Airtable overview & authentication
* **Sidebar title:** Overview & authentication
* **Page content**: authentication with Airtable, in the same format as [this](https://trigger.dev/docs/integrations/apis/github). If there is no overview, write one. You can use their company website for inspiration.

### Airtable Tasks:

* **Page title:** Airtable tasks
* **Sidebar title:** Tasks
* **Page content:** all the tasks available from our Airtable integration, in the same format as this: [https://trigger.dev/docs/integrations/apis/github-tasks](https://trigger.dev/docs/integrations/apis/github-tasks). Please include code comments in all of the code examples. Also include one example at the bottom with clear comments. See references below for sample code.

### References & resources:

* [GitHub documentation](https://trigger.dev/docs/integrations/apis/github) to reference
* Our current [Airtable documentation](https://github.com/triggerdotdev/trigger.dev/blob/main/docs/integrations/apis/airtable.mdx) in the GitHub repo.
* Example job code to use - [job catalog](https://github.com/triggerdotdev/trigger.dev/blob/main/references/job-catalog/src/airtable.ts) and [jobs showcase](https://trigger.dev/showcase?tags=&integrations=airtable).
* We use Mintlify for our docs, [documentation here](https://mintlify.com/docs/quickstart)

> \[!IMPORTANT\]
> Please include a video or screenshots of the pages when you submit a PR for us to check

<sub>[TRI-1431](https://linear.app/triggerdotdev/issue/TRI-1431/improve-the-airtable-integration-documentation)</sub>

### PR DESCRIPTION
**Pull request by shelar1423**
Closes #665 

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/triggerdotdev/trigger.dev/blob/main/CONTRIBUTING.md)
- [x] The PR title follows the convention.
- [x] I ran and tested the code works

---

## Testing

- hosting it locally and making sure code works the way it is supposed to even after the change

---

## Changelog

- added Airtable group with overview and auth , Tasks  as subgroup
- added Airtable-tasks file 
- formatted airtable overview and auth page

---

## Screenshots

image
image
image

💯

### CODE REVIEW

**Comment by shelar1423** [comment]
@D-K-P P have a review.Thank you

**Comment by shelar1423** [comment]
## updated
 @D-K-P 
image
image

**Comment by shelar1423** [comment]
image
image

@D-K-P made the changes , have a look.Thanks

**Comment by D-K-P** [comment]
I'm going to close this one @shelar1423 but I have to make a few little changes. I'll send you a link once i've edited it. Thank you!

**Pull request merged**
