### PR TITLE
Improved the Slack integration documentation 

### LINKED ISSUE #663: [TRI-1429] Improve the Slack integration documentation
## Overview:

Update the [Slack integration documentation](https://trigger.dev/docs/integrations/apis/slack) so it is much easier to use as a reference.

We have just overhauled our [GitHub documentation](https://trigger.dev/docs/integrations/apis/github) and would like all of the rest of our integrations to follow the same structure.

*Please use the references and resources at the bottom of this post to complete this issue.*

### Slack overview & authentication:

This page is currently [this](https://trigger.dev/docs/integrations/apis/slack).

* **Page Title:** Slack overview & authentication
* **Sidebar title:** Overview & authentication
* **Page content**: authentication with Slack, in the same format as [this](https://trigger.dev/docs/integrations/apis/github). If there is no overview, write one. You can use their company website for inspiration.

### Slack Tasks:

* **Page title:** Slack tasks
* **Sidebar title:** Tasks
* **Page content:** all the tasks available from our Slack integration, in the same format as this: [https://trigger.dev/docs/integrations/apis/github-tasks](https://trigger.dev/docs/integrations/apis/github-tasks). Please include code comments in all of the code examples. Also include one example at the bottom with clear comments. See references below for sample code.

### References & resources:

* Our current [Slack documentation](https://github.com/triggerdotdev/trigger.dev/blob/main/docs/integrations/apis/slack.mdx) in the GitHub repo.
* Example job code to use - [job catalog](https://github.com/triggerdotdev/trigger.dev/blob/main/references/job-catalog/src/slack.ts) and [jobs showcase](https://trigger.dev/showcase?tags=&integrations=slack).
* We use Mintlify for our docs, [documentation here](https://mintlify.com/docs/quickstart)

> \[!IMPORTANT\]
> Please include a video or screenshots of the pages when you submit a PR for us to check

<sub>From [SyncLinear.com](https://synclinear.com) | [TRI-1429](https://linear.app/triggerdotdev/issue/TRI-1429/improve-the-slack-integration-documentation)</sub>

### PR DESCRIPTION
**Pull request by shelar1423**
Closes #663 

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/triggerdotdev/trigger.dev/blob/main/CONTRIBUTING.md)
- [x] The PR title follows the convention.
- [x] I ran and tested the code works

---

## Testing

- hosting it locally and making sure code works the way it is supposed to even after the change

---

## Changelog

- added Slack group with overview and auth , Tasks  as subgroup
- added slack-tasks file 
- formatted slack overview and auth page

---

## Screenshots
image
image
image

💯

### CODE REVIEW

**Comment by shelar1423** [comment]
@D-K-P have a review.Thank you

**Comment by shelar1423** [comment]
Yeah sure @D-K-P just le me know the typos I'll fix it

**Comment by D-K-P** [comment]
Hey @shelar1423  - I will review this properly later today, but please make sure you're following the GitHub example. For example the OAuth section should explain how to use OAuth and also link to Slacks documentation so the user can check the scopes - github example here: https://trigger.dev/docs/integrations/apis/github

Also, for the overview, I've just improved GitHubs so it is a bit clearer. Basically we want to write about how you can use Slack with Trigger.dev - https://trigger.dev/docs/integrations/apis/github. Hope that helps!

**Comment by shelar1423** [comment]
@D-K-P sure , meanwhile let me know if the other PR on Airtable is fine .

**Comment by shelar1423** [comment]
## UPDATED
 @D-K-P 
image
image

**Comment by D-K-P** [comment]
Thank you. Almost there:

- For the scopes link - here is an updated URL to change (the one you added was legacy): https://api.slack.com/scopes
- For the task, please change the channel id to "<your-channel-id>
- Could you add a full example 'Example usage' at the bottom of tasks page (see the github docs for an example), you can use one from the jobs showcase

**Comment by shelar1423** [comment]
@D-K-P sure will make the changes right now

**Pull request merged**
