### PR TITLE
feat: adding job run cancelling feature

### LINKED ISSUE #554: [TRI-1363] feat: Allow cancelling job runs from the TriggerClient
### Is your feature request related to a problem? Please describe.

There is currently no way to cancel a job run programmatically.

### Describe the solution you'd like to see

It would be great if there was an instance method exposed on `TriggerClient` that allowed cancelling a run:

```ts
await client.cancelRun(runId)
```

This will require a new endpoint `POST /api/v1/runs/$runId/cancel`.  It should use the `CancelRunService` which is used when cancelling a run from the dashboard. The response body should be the same response as the `GET /api/v1/runs/$runId` endpoint.

### Describe alternate solutions

N/A

### Additional information

_No response_

<sub>[TRI-1363](https://linear.app/triggerdotdev/issue/TRI-1363/feat-allow-cancelling-job-runs-from-the-triggerclient)</sub>

### PR DESCRIPTION
**Pull request by 0x0elliot**
Closes #554 

## ✅ Checklist

- [x] I have followed every step in the [contributing guide](https://github.com/triggerdotdev/trigger.dev/blob/main/CONTRIBUTING.md)
- [x] The PR title follows the convention.
- [x] I ran and tested the code works

---

## Testing

- Verified the SDK change
- Verified the API change

---

## Changelog

Added in the requested features.

---

## Screenshots
Screenshot 2023-10-05 at 7 21 15 AM
Screenshot 2023-10-05 at 7 21 31 AM

💯

### CODE REVIEW

**Comment by 0x0elliot** [comment]
draft because i need to do some changes.

**Comment by 0x0elliot** [comment]
saw a bug in the SDK. let me fix that before the merge.

**Comment by 0x0elliot** [comment]
should be good now!

**Comment by ericallam** [comment]
Thanks @0x0elliot for your attempt! There is another PR open for this feature as well #562 that is a little closer to what we were looking for. You can either:

- Work with @hmacr on #562 to get the feature over the line
- Update this PR to be more in-line with #562 while addressing the review comments I left there
- Close this PR

**Pull request closed without merging**
