### PR TITLE
feature/TRI 712/create eslint plugin to ensure uniqueness on task keys

### PR DESCRIPTION
**Pull request by ologbonowiwi**
/claim #206 

- test: add test to no-duplicated-task-keys rule
- feat: implement no-duplicated-task-keys
- chore: create testing scripts
- refactor: fill in rule meta
- feat: export no-duplicated-task-keys rule
- chore: bump package version to 0.0.1

### CODE REVIEW

**Comment by ologbonowiwi** [comment]
@ericallam got the rule working (you can enter `config-packages/eslint-config-custom` and run `pnpm test` or `pnpm test:watch` to take a look at it working).

**Comment by ologbonowiwi** [comment]
Although the rule was successfully implemented, I hadn't success in getting it to validate an actual code. It would be nice to get some help on doing so, if possible 😄

**Comment by matt-aitken** [comment]
@ologbonowiwi this is great. I think the idea was that this would be a published package, so it would live in the `packages` folder and be public. That way we could get the CLI to install it so people can use it. (We'd have manual installation as well).

**Comment by ologbonowiwi** [comment]
@matt-aitken fixed it to match what we currently need.

To test it, you can enter any `examples/nextjs-example` with access to jobs, create a job with a duplicated key and run `pnpm lint`.

The expectation is that you'll see the error on your console.

**Pull request merged**
