### PR TITLE
docs: supabase guide without pooling section

### PR DESCRIPTION
**Pull request by nicktrn**
Just a quick PR so you can publish in time for the blog post! @ericallam

### CODE REVIEW

**Comment by ericallam** [comment]
Legend, nice work!

**Comment by ericallam** [comment]
https://trigger.dev/docs/documentation/guides/self-hosting/supabase

**Comment by nicktrn** [comment]
Ha, this is great, thanks for the attribution! Glad you lot have a good sense of humour. A true classic :laughing:

**Comment by nicktrn** [comment]
Tracking this here in case [Postgres Extensions](https://www.prisma.io/docs/concepts/components/prisma-schema/postgresql-extensions#how-to-enable-the-postgresqlextensions-preview-feature) are ever added to the Prisma schema:
- https://github.com/prisma/prisma/issues/19100

**Pull request merged**
